version: "3"

services: 
    nginx:
        image: nginx:stable-alpine
        ports:
            - "80:80"
        volumes: 
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on: 
            - api
            - mongo

    api:
        build:
            dockerfile: Dockerfile
            context: ./server

    mongo:
        image: mongo
        env_file:
            - ./server/config/.env
        environment: 
            - MONGO_INITDB_ROOT_USERNAME=jamm3e3333
            - MONGO_INITDB_ROOT_PASSWORD=ahoj123
        volumes:
            - mongo-db:/data/db

volumes:
    mongo-db:
        