version: "3"

services: 
    api:
        build:
            dockerfile: Dockerfile
            context: ./server
        ports:
            - "3010:3010"
        depends_on:
            - mongo

    mongo:
        image: mongo
        env_file:
            - ./server/config/.env
        environment: 
            - MONGO_INITDB_ROOT_USERNAME=jamm3e3333
            - MONGO_INITDB_ROOT_PASSWORD=ahoj123
        volumes:
            - mongo-db:/data/db #named volume - must have declaration

# list of all named volumes              
volumes:
    mongo-db:
        