version: "3"

services: 
    nginx:
        image: nginx:stable-alpine
        volumes: 
            - /nginx/defualt.conf:/etc/nginx/conf.d/default.conf:ro
        ports:
            - "80:80"

    server:
        build:
            dockerfile: Dockerfile
            context: ./server

    mongo:
        image: mongo
        env_file:
            - /server/config/.env
        environment: 
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_PASSWORD}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
        volumes:
            - mongo-db:/data/db
        